### PR TITLE
fixed lint error

### PR DESCRIPTION
**Pull request by NeXTs**
that was caused by using `"`

### CODE REVIEW

**Comment by keyz** [comment]
Thanks @NeXTs, but I don't think there's a lint error. Did you pick up my ESLint config (the Airbnb one)? `npm run lint` works fine for me here.

**Comment by NeXTs** [comment]
sure thing I picked your ESLint config.
All I did to reproduce this were:

`npm i`
`npm run lint`

**Comment by keyz** [comment]
Hmm that's weird -- sorry about closing this early but seems like it's fine on my end:

```
$ npmr lint

> react-atv-img@0.1.1 lint /Users/kz/kz/react-atv-img
> eslint src

$
```

**Comment by NeXTs** [comment]
indeed strange
okay then, no problems )

**Pull request closed without merging**
